# frozen_string_literal: true

source 'https://rubygems.org'

gem 'base_gem', git: 'git@github.com:ajorgensen/bundler-poc.git', glob: 'gems/**/*.gemspec'
gem 'some_gem', git: 'git@github.com:ajorgensen/bundler-poc.git', glob: 'gems/**/*.gemspec'

gemspec
